### ISSUE TITLE
Read the current log file in UWP

### ISSUE THREAD

**Issue by simonaghinea** [novotnyllc/MetroLog#107]
I cannot read the current log file in UWP, it seems that the file remains locked.
Is there a way to unlock the file or force a close? I have no problem reading older files. The logger is configured to create a log file each day.

**Comment by ThomasFerro** [comment]
Have you tried to set the **StreamingFileTarget**'s property *KeepLogFilesOpenForWrite* to *false* ?

```
var fileTarget = new StreamingFileTarget()
{
    KeepLogFilesOpenForWrite = false
};
```

**Comment by simonaghinea** [comment]
Thank you, that was it! I was almost sure I have already tried setting it on false :D
