### ISSUE TITLE
NuGet targets portable-net45+wp8+win8+wpa81, wpa81, win81 collide when combining UAP and Portable Library into APPX

### ISSUE THREAD

**Issue by PaulosV** [novotnyllc/MetroLog#84]
After upgrading to 1.0.1, I discovered that the Visual Studio won't build my Win8.1/WP8.1 package, because `MetroLog.pdb` from one folder collides with `MetroLog.pdb` from another folder in `packages` folder.

The error message follows:

```
C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\AppxPackage\Microsoft.AppXPackage.Targets(1670,5): // repeating
error APPX1101: Payload contains two or more files with the same destination path 'MetroLog.pdb'. Source files: 
error APPX1101: I:\Documents\Projekty\stupid things\MetroLogDepApp\packages\MetroLog.1.0.1\lib\win81\MetroLog.pdb
error APPX1101: I:\Documents\Projekty\stupid things\MetroLogDepApp\packages\MetroLog.1.0.1\lib\portable-net45+wp8+win8+wpa81\MetroLog.pdb

error APPX1101: Payload contains two or more files with the same destination path 'MetroLog.pdb'. Source files: 
error APPX1101: I:\Documents\Projekty\stupid things\MetroLogDepApp\packages\MetroLog.1.0.1\lib\wpa81\MetroLog.pdb
error APPX1101: I:\Documents\Projekty\stupid things\MetroLogDepApp\packages\MetroLog.1.0.1\lib\portable-net45+wp8+win8+wpa81\MetroLog.pdb
```

Attached is an empty Win81/WPA81 project with a portable library targeted to Win81/WPA81. This combination triggers the error for me.

[MetroLogDepApp.zip](https://github.com/onovotny/MetroLog/files/286706/MetroLogDepApp.zip)

I could, supposedly, use different target for the universal Win81 project, but is it reasonable?
This issue started appearing since 1.0.0.

**Comment by clairernovotny** [comment]
Can you try converting your `packages.config` to `project.json` as detailed in this blog post:
https://oren.codes/2016/02/08/project-json-all-the-things/

It should solve your issues as project.json handles transitive references significantly better.

**Comment by PaulosV** [comment]
I tried it on that simple project and it indeed did solve the issue! Thanks for this, I'll try to convert it in our big project and we'll see how that goes.

**Comment by PaulosV** [comment]
Aaand indeed it helped! Thank you again, I'm closing it, I hope you won't mind :)
